broker:
  host: localhost
  port: 1883
bridge:
  ros2mqtt:
    - ros_topic: /ping/ros
      mqtt_topic: pingpong/ros
    - ros_topic: /ping/json
      mqtt_topic: pingpong/json
      json: true
    - ros_topic: /ping/primitive
      mqtt_topic: pingpong/primitive
      primitive: true
  mqtt2ros:
    - mqtt_topic: pingpong/ros
      ros_topic: /pong/ros
    - mqtt_topic: pingpong/json
      ros_topic: /pong/json
      json: true
    - mqtt_topic: pingpong/primitive
      ros_topic: /pong/primitive
      primitive: true