# This service is used to dynamically register new MQTT -> ROS2 mappings. 
# Syntax is the same as the ones used on config files.
# Remember to also register ROS2 -> MQTT.
string ros_topic
string mqtt_topic 
bool primitive false 
uint8 mqtt_qos 0
uint32 ros_queue_size 1
bool ros_latched false
---

