name: industrial_ci

on: pull_request

jobs:
  industrial_ci:
    name: ros2-${{ matrix.ROS_DISTRO }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO:
          - humble
          - jazzy
          - kilted
          - lyrical
        ROS_REPO:
          - main
        include:
          - ROS_DISTRO: rolling
            ROS_REPO: main
            DOCKER_IMAGE: ros:rolling-ros-base # default image does not work with rolling
    steps:
      - uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{ toJSON(matrix) }}
